// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package io.flutter.plugins.camera;

import android.app.Activity;
import android.hardware.camera2.CameraAccessException;
import android.hardware.camera2.CameraCharacteristics;
import android.hardware.camera2.CameraManager;
import android.hardware.camera2.params.StreamConfigurationMap;
import android.media.CamcorderProfile;
import android.os.Handler;
import android.os.Looper;
import android.util.Range;
import android.util.Size;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.VisibleForTesting;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.EventChannel;
import io.flutter.plugins.camera.CameraPermissions.PermissionsRegistry;
import io.flutter.plugins.camera.features.CameraFeatureFactoryImpl;
import io.flutter.plugins.camera.features.Point;
import io.flutter.plugins.camera.features.exposurelock.ExposureMode;
import io.flutter.plugins.camera.features.flash.FlashMode;
import io.flutter.plugins.camera.features.resolution.ResolutionPreset;
import io.flutter.view.TextureRegistry;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

final class CameraApiImpl implements Messages.CameraApi {
  private final Activity activity;
  private final BinaryMessenger messenger;
  private final CameraPermissions cameraPermissions;
  private final PermissionsRegistry permissionsRegistry;
  private final TextureRegistry textureRegistry;
  private final EventChannel imageStreamChannel;
  @VisibleForTesting @Nullable Camera camera;

  CameraApiImpl(
      Activity activity,
      BinaryMessenger messenger,
      CameraPermissions cameraPermissions,
      PermissionsRegistry permissionsAdder,
      TextureRegistry textureRegistry) {
    this.activity = activity;
    this.messenger = messenger;
    this.cameraPermissions = cameraPermissions;
    this.permissionsRegistry = permissionsAdder;
    this.textureRegistry = textureRegistry;

    imageStreamChannel =
        new EventChannel(messenger, "plugins.flutter.io/camera_android/imageStream");
    Messages.CameraApi.setUp(messenger, this);
  }

  void tearDownMessageHandler() {
    Messages.CameraApi.setUp(messenger, null);
  }

  private Long instantiateCamera(String cameraName, Messages.PlatformMediaSettings settings)
      throws CameraAccessException {
    TextureRegistry.SurfaceTextureEntry flutterSurfaceTexture =
        textureRegistry.createSurfaceTexture();
    long cameraId = flutterSurfaceTexture.id();
    DartMessenger dartMessenger =
        new DartMessenger(
            new Handler(Looper.getMainLooper()),
            new Messages.CameraGlobalEventApi(messenger),
            new Messages.CameraEventApi(messenger, String.valueOf(cameraId)));
    CameraProperties cameraProperties =
        new CameraPropertiesImpl(cameraName, CameraUtils.getCameraManager(activity));
    Integer fps = (settings.getFps() == null) ? null : settings.getFps().intValue();
    Integer videoBitrate =
        (settings.getVideoBitrate() == null) ? null : settings.getVideoBitrate().intValue();
    Integer audioBitrate =
        (settings.getAudioBitrate() == null) ? null : settings.getAudioBitrate().intValue();

    // Extract resolution from settings
    Messages.PlatformCameraResolution resolution = settings.getResolution();
    Size cameraResolution = new Size(resolution.getWidth().intValue(), resolution.getHeight().intValue());

    camera =
        new Camera(
            activity,
            flutterSurfaceTexture,
            new CameraFeatureFactoryImpl(),
            dartMessenger,
            cameraProperties,
            new Camera.VideoCaptureSettings(
                cameraResolution, settings.getEnableAudio(), fps, videoBitrate, audioBitrate));

    return flutterSurfaceTexture.id();
  }

  @SuppressWarnings("ConstantConditions")
  private <T> void handleException(Exception exception, Messages.Result<T> result) {
    // The code below exactly preserves the format of the native exceptions generated by pre-Pigeon
    // code. Since `camera` currently leaks the raw platform exceptions to clients, there may be client
    // code that relies on specific string values here, so these should not be changed. See
    // https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#platform-exception-handling
    // for longer-term solutions to this.
    if (exception instanceof CameraAccessException) {
      result.error(new Messages.FlutterError("CameraAccess", exception.getMessage(), null));
      return;
    }
    result.error(new Messages.FlutterError("error", exception.getMessage(), null));
  }

  private void handleException(Exception exception, Messages.VoidResult result) {
    // The code below exactly preserves the format of the native exceptions generated by pre-Pigeon
    // code. Since `camera` currently leaks the raw platform exceptions to clients, there may be client
    // code that relies on specific string values here, so these should not be changed. See
    // https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#platform-exception-handling
    // for longer-term solutions to this.
    if (exception instanceof CameraAccessException) {
      result.error(new Messages.FlutterError("CameraAccess", exception.getMessage(), null));
      return;
    }
    result.error(new Messages.FlutterError("error", exception.getMessage(), null));
  }

  @NonNull
  @Override
  public List<Messages.PlatformCameraDescription> getAvailableCameras() {
    if (activity == null) {
      return Collections.emptyList();
    }
    try {
      return CameraUtils.getAvailableCameras(activity);
    } catch (CameraAccessException e) {
      throw new RuntimeException(e);
    }
  }

  @NonNull
  @Override
  public List<Messages.PlatformCameraResolution> getAvailableResolutions(@NonNull String cameraName) {
    android.util.Log.d("CameraApiImpl", "getAvailableResolutions called for camera: " + cameraName);

    if (activity == null) {
      android.util.Log.w("CameraApiImpl", "Activity is null, returning empty list");
      return Collections.emptyList();
    }

    try {
      CameraManager cameraManager = CameraUtils.getCameraManager(activity);
      CameraCharacteristics characteristics = cameraManager.getCameraCharacteristics(cameraName);

      StreamConfigurationMap map = characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);
      if (map == null) {
        return Collections.emptyList();
      }

      // Get output sizes for JPEG format (streamable resolutions - equivalent to preview sizes)
      Size[] standardJpegSizes = map.getOutputSizes(android.graphics.ImageFormat.JPEG);

      // Get high-resolution output sizes (still capture modes - equivalent to picture sizes, API 23+)
      Size[] highResJpegSizes = null;
      if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
        highResJpegSizes = map.getHighResolutionOutputSizes(android.graphics.ImageFormat.JPEG);
      }

      // Get sensor active array size (maximum hardware resolution)
      android.graphics.Rect activeArraySize = characteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE);
      Size sensorMaxSize = null;
      if (activeArraySize != null) {
        sensorMaxSize = new Size(activeArraySize.width(), activeArraySize.height());
      }

      // Combine all resolution sources into a Set (auto-deduplicates)
      java.util.Set<Size> allSizesSet = new java.util.HashSet<>();

      if (standardJpegSizes != null) {
        for (Size size : standardJpegSizes) {
          allSizesSet.add(size);
        }
      }

      if (highResJpegSizes != null) {
        for (Size size : highResJpegSizes) {
          allSizesSet.add(size);
        }
      }

      if (sensorMaxSize != null) {
        allSizesSet.add(sensorMaxSize);
      }

      // Convert Set to array and sort by pixel count (descending)
      Size[] outputSizes = allSizesSet.toArray(new Size[0]);
      java.util.Arrays.sort(outputSizes, (a, b) -> {
        int pixelsA = a.getWidth() * a.getHeight();
        int pixelsB = b.getWidth() * b.getHeight();
        return Integer.compare(pixelsB, pixelsA); // Descending order
      });

      if (outputSizes.length == 0) {
        android.util.Log.d("CameraApiImpl", "No JPEG output sizes available for camera: " + cameraName);
        return Collections.emptyList();
      }

      // Debug: Log all available JPEG resolutions
      android.util.Log.d("CameraApiImpl", "Camera " + cameraName + " resolution sources:");
      android.util.Log.d("CameraApiImpl", "  Standard JPEG sizes: " + (standardJpegSizes != null ? standardJpegSizes.length : 0));
      android.util.Log.d("CameraApiImpl", "  High-res JPEG sizes: " + (highResJpegSizes != null ? highResJpegSizes.length : 0));
      android.util.Log.d("CameraApiImpl", "  Sensor max size: " + (sensorMaxSize != null ? sensorMaxSize.getWidth() + "×" + sensorMaxSize.getHeight() : "null"));
      android.util.Log.d("CameraApiImpl", "Camera " + cameraName + " has " + outputSizes.length + " total unique JPEG resolutions:");
      for (Size size : outputSizes) {
        android.util.Log.d("CameraApiImpl", "  - " + size.getWidth() + "×" + size.getHeight());
      }

      // Get available FPS ranges
      Range<Integer>[] fpsRanges = characteristics.get(CameraCharacteristics.CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES);

      // Use a default FPS range if none available
      int defaultMinFps = 15;
      int defaultMaxFps = 30;
      if (fpsRanges != null && fpsRanges.length > 0) {
        // Find the range with highest max FPS
        for (Range<Integer> range : fpsRanges) {
          if (range.getUpper() > defaultMaxFps) {
            defaultMinFps = range.getLower();
            defaultMaxFps = range.getUpper();
          }
        }
      }

      List<Messages.PlatformCameraResolution> resolutions = new ArrayList<>();
      for (Size size : outputSizes) {
        Messages.PlatformCameraResolution resolution = new Messages.PlatformCameraResolution.Builder()
            .setWidth((long) size.getWidth())
            .setHeight((long) size.getHeight())
            .setMinFps((long) defaultMinFps)
            .setMaxFps((long) defaultMaxFps)
            .build();
        resolutions.add(resolution);
      }

      return resolutions;
    } catch (CameraAccessException e) {
      throw new RuntimeException("Failed to get available resolutions for camera: " + cameraName, e);
    }
  }

  @Override
  public void getAvailableVideoResolutions(@NonNull String cameraName, @NonNull Messages.Result<List<Messages.PlatformCameraResolution>> result) {
    android.util.Log.d("CameraApiImpl", "getAvailableVideoResolutions called for camera: " + cameraName);

    if (activity == null) {
      android.util.Log.w("CameraApiImpl", "Activity is null, returning empty list");
      result.success(Collections.emptyList());
      return;
    }

    int cameraId;
    try {
      cameraId = Integer.parseInt(cameraName);
    } catch (NumberFormatException e) {
      android.util.Log.e("CameraApiImpl", "Invalid camera name: " + cameraName);
      result.success(Collections.emptyList());
      return;
    }

    try {
      // Query all available CamcorderProfile quality levels
      java.util.Set<Size> videoSizesSet = new java.util.HashSet<>();

      int[] qualityLevels = {
        CamcorderProfile.QUALITY_2160P,  // 4K (3840×2160)
        CamcorderProfile.QUALITY_1080P,  // 1080p (1920×1080)
        CamcorderProfile.QUALITY_720P,   // 720p (1280×720)
        CamcorderProfile.QUALITY_480P,   // 480p (640×480)
        CamcorderProfile.QUALITY_QVGA,   // QVGA
        CamcorderProfile.QUALITY_HIGH,   // Highest available
        CamcorderProfile.QUALITY_LOW     // Lowest available
      };

      for (int quality : qualityLevels) {
        if (CamcorderProfile.hasProfile(cameraId, quality)) {
          CamcorderProfile profile = CamcorderProfile.get(cameraId, quality);
          videoSizesSet.add(new Size(profile.videoFrameWidth, profile.videoFrameHeight));
        }
      }

      // Convert Set to array and sort by pixel count (descending)
      Size[] videoSizes = videoSizesSet.toArray(new Size[0]);
      java.util.Arrays.sort(videoSizes, (a, b) -> {
        int pixelsA = a.getWidth() * a.getHeight();
        int pixelsB = b.getWidth() * b.getHeight();
        return Integer.compare(pixelsB, pixelsA);
      });

      if (videoSizes.length == 0) {
        android.util.Log.w("CameraApiImpl", "No video resolutions found for camera: " + cameraName);
        result.success(Collections.emptyList());
        return;
      }

      // Debug logging
      android.util.Log.d("CameraApiImpl", "Camera " + cameraName + " has " + videoSizes.length + " video resolutions from CamcorderProfile:");
      for (Size size : videoSizes) {
        android.util.Log.d("CameraApiImpl", "  - " + size.getWidth() + "×" + size.getHeight());
      }

      // Get FPS ranges
      CameraManager cameraManager = CameraUtils.getCameraManager(activity);
      CameraCharacteristics characteristics = cameraManager.getCameraCharacteristics(cameraName);
      Range<Integer>[] fpsRanges = characteristics.get(CameraCharacteristics.CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES);

      int defaultMinFps = 15;
      int defaultMaxFps = 30;
      if (fpsRanges != null && fpsRanges.length > 0) {
        for (Range<Integer> range : fpsRanges) {
          if (range.getUpper() > defaultMaxFps) {
            defaultMinFps = range.getLower();
            defaultMaxFps = range.getUpper();
          }
        }
      }

      // Convert to PlatformCameraResolution list
      List<Messages.PlatformCameraResolution> resolutions = new ArrayList<>();
      for (Size size : videoSizes) {
        Messages.PlatformCameraResolution resolution = new Messages.PlatformCameraResolution.Builder()
            .setWidth((long) size.getWidth())
            .setHeight((long) size.getHeight())
            .setMinFps((long) defaultMinFps)
            .setMaxFps((long) defaultMaxFps)
            .build();
        resolutions.add(resolution);
      }

      result.success(resolutions);

    } catch (CameraAccessException e) {
      result.error(new Messages.FlutterError("CAMERA_ACCESS_ERROR", "Failed to get video resolutions for camera: " + cameraName, null));
    }
  }

  @Override
  public void create(
      @NonNull String cameraName,
      @NonNull Messages.PlatformMediaSettings settings,
      @NonNull Messages.Result<Long> result) {
    if (camera != null) {
      camera.close();
    }

    cameraPermissions.requestPermissions(
        activity,
        permissionsRegistry,
        settings.getEnableAudio(),
        (String errCode, String errDesc) -> {
          if (errCode == null) {
            try {
              result.success(instantiateCamera(cameraName, settings));
            } catch (Exception e) {
              handleException(e, result);
            }
          } else {
            result.error(new Messages.FlutterError(errCode, errDesc, null));
          }
        });
  }

  @Override
  public void initialize(@NonNull Messages.PlatformImageFormatGroup imageFormat) {
    if (camera == null) {
      throw new Messages.FlutterError(
          "cameraNotFound",
          "Camera not found. Please call the 'create' method before calling 'initialize'.",
          null);
    }
    try {
      camera.open(CameraUtils.imageFormatGroupFromPigeon(imageFormat));
    } catch (CameraAccessException e) {
      throw new Messages.FlutterError("CameraAccessException", e.getMessage(), null);
    }
  }

  @Override
  public void takePicture(@NonNull Messages.Result<String> result) {
    camera.takePicture(result);
  }

  @Override
  public void startVideoRecording(@NonNull Boolean enableStream) {
    camera.startVideoRecording(enableStream ? imageStreamChannel : null);
  }

  @NonNull
  @Override
  public String stopVideoRecording() {
    return camera.stopVideoRecording();
  }

  @Override
  public void pauseVideoRecording() {
    camera.pauseVideoRecording();
  }

  @Override
  public void resumeVideoRecording() {
    camera.resumeVideoRecording();
  }

  @Override
  public void setFlashMode(
      @NonNull Messages.PlatformFlashMode flashMode, @NonNull Messages.VoidResult result) {
    FlashMode mode = CameraUtils.flashModeFromPigeon(flashMode);
    try {
      camera.setFlashMode(result, mode);
    } catch (Exception e) {
      handleException(e, result);
    }
  }

  @Override
  public void setExposureMode(
      @NonNull Messages.PlatformExposureMode exposureMode, @NonNull Messages.VoidResult result) {
    ExposureMode mode = CameraUtils.exposureModeFromPigeon(exposureMode);
    try {
      camera.setExposureMode(result, mode);
    } catch (Exception e) {
      handleException(e, result);
    }
  }

  @Override
  public void setExposurePoint(
      @Nullable Messages.PlatformPoint point, @NonNull Messages.VoidResult result) {
    try {
      camera.setExposurePoint(result, point == null ? null : new Point(point.getX(), point.getY()));
    } catch (Exception e) {
      handleException(e, result);
    }
  }

  @NonNull
  @Override
  public Double getMinExposureOffset() {
    return camera.getMinExposureOffset();
  }

  @NonNull
  @Override
  public Double getMaxExposureOffset() {
    return camera.getMaxExposureOffset();
  }

  @NonNull
  @Override
  public Double getExposureOffsetStepSize() {
    return camera.getExposureOffsetStepSize();
  }

  @Override
  public void setExposureOffset(@NonNull Double offset, @NonNull Messages.Result<Double> result) {
    try {
      camera.setExposureOffset(result, offset);
    } catch (Exception e) {
      handleException(e, result);
    }
  }

  @Override
  public void setFocusMode(@NonNull Messages.PlatformFocusMode focusMode) {
    camera.setFocusMode(CameraUtils.focusModeFromPigeon(focusMode));
  }

  @Override
  public void setFocusPoint(
      @Nullable Messages.PlatformPoint point, @NonNull Messages.VoidResult result) {
    try {
      camera.setFocusPoint(result, point == null ? null : new Point(point.getX(), point.getY()));
    } catch (Exception e) {
      handleException(e, result);
    }
  }

  @Override
  public void startImageStream() {
    try {
      camera.startPreviewWithImageStream(imageStreamChannel);
    } catch (CameraAccessException e) {
      throw new Messages.FlutterError("CameraAccessException", e.getMessage(), null);
    }
  }

  @Override
  public void stopImageStream() {
    try {
      // Don't wait for start preview
      camera.startPreview(null);
    } catch (Exception e) {
      throw new Messages.FlutterError(e.getClass().getName(), e.getMessage(), null);
    }
  }

  @NonNull
  @Override
  public Double getMaxZoomLevel() {
    assert camera != null;
    return (double) camera.getMaxZoomLevel();
  }

  @NonNull
  @Override
  public Double getMinZoomLevel() {
    assert camera != null;
    return (double) camera.getMinZoomLevel();
  }

  @Override
  public void setZoomLevel(@NonNull Double zoom, @NonNull Messages.VoidResult result) {
    assert camera != null;
    camera.setZoomLevel(result, zoom.floatValue());
  }

  @Override
  public void lockCaptureOrientation(
      @NonNull Messages.PlatformDeviceOrientation platformOrientation) {
    camera.lockCaptureOrientation(CameraUtils.orientationFromPigeon(platformOrientation));
  }

  @Override
  public void unlockCaptureOrientation() {
    camera.unlockCaptureOrientation();
  }

  @Override
  public void setSensorOrientation(@NonNull Long degrees) {
    camera.setSensorOrientation(degrees.intValue());
  }

  @Override
  public void pausePreview() {
    try {
      camera.pausePreview();
    } catch (CameraAccessException e) {
      throw new Messages.FlutterError("CameraAccessException", e.getMessage(), null);
    }
  }

  @Override
  public void resumePreview() {
    camera.resumePreview();
  }

  @Override
  public void setDescriptionWhileRecording(@NonNull String cameraName) {
    try {
      camera.setDescriptionWhileRecording(
          new CameraPropertiesImpl(cameraName, CameraUtils.getCameraManager(activity)));
    } catch (CameraAccessException e) {
      throw new Messages.FlutterError("CameraAccessException", e.getMessage(), null);
    }
  }

  @Override
  public void dispose() {
    if (camera != null) {
      camera.dispose();
    }
  }
}
